import 'package:flutter/material.dart';
import '../../features/hangly_scene/physics/charm_metrics.dart';
import 'charm.dart';

class CharmCatalog {
  static const List<CharmCategory> categories = [
    CharmCategory(id: 'all', name: 'All Charms', icon: Icons.auto_awesome),
    CharmCategory(id: 'protection', name: 'Protection', icon: Icons.shield),
    CharmCategory(id: 'luck', name: 'Luck & Fortune', icon: Icons.monetization_on),
    CharmCategory(id: 'ritual', name: 'Ritual & Home', icon: Icons.home),
    CharmCategory(id: 'classic', name: 'Classic', icon: Icons.star),
    CharmCategory(id: 'marvel', name: 'Marvel', icon: Icons.flash_on),
    CharmCategory(id: 'dc', name: 'DC', icon: Icons.shield_outlined),
    CharmCategory(id: 'tamilSpiritual', name: 'Tamil Spiritual', icon: Icons.brightness_7),
    CharmCategory(id: 'bts', name: 'BTS', icon: Icons.favorite),
    CharmCategory(id: 'footballLegends', name: 'Football Legends', icon: Icons.sports_soccer),
    CharmCategory(id: 'musicLegends', name: 'Music Legends', icon: Icons.music_note),
    CharmCategory(id: 'friends', name: 'Friends', icon: Icons.coffee),
    CharmCategory(id: 'breakingBad', name: 'Breaking Bad', icon: Icons.science),
    CharmCategory(id: 'strangerThings', name: 'Stranger Things', icon: Icons.lightbulb),
  ];

  static const Charm defaultCharm = Charm(
    id: 'nazar',
    name: 'Nazar boncuğu',
    category: 'protection',
    assetPath: 'assets/charms/Nazar Boncuğu.svg',
    metrics: CharmMetrics(mass: 2.75, radiusRatio: 0.145, knotInset: 0.90),
    primaryColor: Color(0xFF1938AD),
    description: 'A glass eye bead hung to deflect the evil eye, the envious glance believed to bring misfortune.',
  );

  static const List<Charm> all = [
  Charm(
    id: 'nazar',
    name: 'Nazar boncuğu',
    category: 'protection',
    assetPath: 'assets/charms/Nazar Boncuğu.svg',
    metrics: CharmMetrics(mass: 2.75, radiusRatio: 0.145, knotInset: 0.90),
    primaryColor: Color(0xFF1938AD),
    description: "A glass eye bead hung to deflect the evil eye, the envious glance believed to bring misfortune. Found across Turkey, Greece and the wider Mediterranean, on doorways, cradles and dashboards alike.",
  ),
  Charm(
    id: 'hamsa',
    name: 'Hamsa',
    category: 'protection',
    assetPath: 'assets/charms/Hamsa.svg',
    metrics: CharmMetrics(mass: 3.05, radiusRatio: 0.158, knotInset: 0.90),
    primaryColor: Color(0xFF263D99),
    description: "An open right hand, often with an eye in the palm, carried as protection against harm. Shared by Jewish, Muslim and Christian communities from Morocco to the Levant.",
  ),
  Charm(
    id: 'nimbuMirchi',
    name: 'Nimbu-mirchi',
    category: 'protection',
    assetPath: 'assets/charms/Nimbu-mirchi.svg',
    metrics: CharmMetrics(mass: 2.85, radiusRatio: 0.152, knotInset: 0.90),
    primaryColor: Color(0xFFF9D62D),
    description: "A lemon and green chillies strung together and hung at shop doors and on vehicles across India to ward off the evil eye, and to give bad luck something sour to chew on instead.",
  ),
  Charm(
    id: 'ghanta',
    name: 'Ghanta',
    category: 'ritual',
    assetPath: 'assets/charms/Ghanta.svg',
    metrics: CharmMetrics(mass: 4.05, radiusRatio: 0.15, knotInset: 0.90),
    primaryColor: Color(0xFFC17238),
    description: "The temple bell of Hindu and Buddhist worship. Its ring is said to clear the mind of the person who strikes it and to announce their arrival to the divine.",
  ),
  Charm(
    id: 'drishtiBommai',
    name: 'Drishti bommai',
    category: 'protection',
    assetPath: 'assets/charms/Dhrishti bomma.svg',
    metrics: CharmMetrics(mass: 3.25, radiusRatio: 0.164, knotInset: 0.90),
    primaryColor: Color(0xFFDB231E),
    description: "A fierce painted face hung outside homes and building sites in Tamil Nadu. Its job is to draw the evil eye onto itself and away from whatever it guards.",
  ),
  Charm(
    id: 'panchangJie',
    name: 'Pánchángjié',
    category: 'luck',
    assetPath: 'assets/charms/Pánchang Jié.svg',
    metrics: CharmMetrics(mass: 2.45, radiusRatio: 0.16, knotInset: 0.90),
    primaryColor: Color(0xFFE0232D),
    description: "The endless knot, tied from a single red cord with no beginning and no end. A symbol of longevity, unity and good fortune, hung at Lunar New Year.",
  ),
  Charm(
    id: 'daruma',
    name: 'Daruma',
    category: 'luck',
    assetPath: 'assets/charms/Daruma.svg',
    metrics: CharmMetrics(mass: 3.65, radiusRatio: 0.154, knotInset: 0.90),
    primaryColor: Color(0xFFE01E1E),
    description: "A round, weighted doll modelled on the monk Bodhidharma. You paint one eye while making a wish and the other when it comes true, and it always rights itself when knocked over.",
  ),
  Charm(
    id: 'manekiNeko',
    name: 'Maneki-neko',
    category: 'luck',
    assetPath: 'assets/charms/Maneki-neko.svg',
    metrics: CharmMetrics(mass: 3.45, radiusRatio: 0.167, knotInset: 0.90),
    primaryColor: Color(0xFFF7F2E5),
    description: "The beckoning cat, raised paw inviting good fortune through the door. A raised right paw is said to bring money; a raised left paw brings customers.",
  ),
  Charm(
    id: 'horseshoe',
    name: 'Horseshoe',
    category: 'luck',
    assetPath: 'assets/charms/Horseshoe.svg',
    metrics: CharmMetrics(mass: 3.85, radiusRatio: 0.151, knotInset: 0.90),
    primaryColor: Color(0xFF9399A3),
    description: "Iron shaped by fire, nailed above a door for luck. Hung open end up it holds the luck in; open end down it pours the luck over those who pass beneath.",
  ),
  Charm(
    id: 'scarab',
    name: 'Scarab',
    category: 'protection',
    assetPath: 'assets/charms/Scarab.svg',
    metrics: CharmMetrics(mass: 3.15, radiusRatio: 0.146, knotInset: 0.90),
    primaryColor: Color(0xFF33BCC1),
    description: "The dung beetle, sacred to the sun's rebirth each morning as it rolls its ball across the sky. Worn as an amulet in ancient Egypt for protection and renewal.",
  ),
  Charm(
    id: 'himmeli',
    name: 'Himmeli',
    category: 'ritual',
    assetPath: 'assets/charms/Himmeli.svg',
    metrics: CharmMetrics(mass: 2.35, radiusRatio: 0.169, knotInset: 0.90),
    primaryColor: Color(0xFFD1A342),
    description: "A geometric mobile of rye straw hung above the table at midwinter in Finland to bless the coming harvest. The name comes from the Swedish word for sky.",
  ),
  Charm(
    id: 'dreamCatcher',
    name: 'Dream Catcher',
    category: 'protection',
    assetPath: 'assets/charms/Dream Catcher.svg',
    metrics: CharmMetrics(mass: 2.52, radiusRatio: 0.1686, knotInset: 0.90),
    primaryColor: Color(0xFF9E7C51),
    description: "An Ojibwe hoop webbed like a spider's, hung over a sleeping child so the bad dreams catch in the net and the good ones slip through the middle and down the feathers.",
  ),
  Charm(
    id: 'spiderMan',
    name: 'Spider-Man',
    category: 'marvel',
    assetPath: 'assets/charms/Avengers/Spider-Man.svg',
    metrics: CharmMetrics(mass: 2.96, radiusRatio: 0.1525, knotInset: 0.90),
    primaryColor: Color(0xFF872B42),
    description: "Hanging head-down from a thread of his own, which is the way he is most often drawn and the only pose in this set that was already a charm before anybody hung it. Pair him with Spider Thread.",
  ),
  Charm(
    id: 'captainAmericaShield',
    name: 'Captain America Shield',
    category: 'marvel',
    assetPath: 'assets/charms/Avengers/Captain-America.svg',
    metrics: CharmMetrics(mass: 3.46, radiusRatio: 0.1515, knotInset: 0.90),
    primaryColor: Color(0xFFB2212B),
    description: "Concentric rings and a white star, struck face on. The heaviest thing in the set after the hammer, and it hangs like it.",
  ),
  Charm(
    id: 'ironManHelmet',
    name: 'Iron Man Helmet',
    category: 'marvel',
    assetPath: 'assets/charms/Avengers/Iron-Man.svg',
    metrics: CharmMetrics(mass: 3.26, radiusRatio: 0.1495, knotInset: 0.90),
    primaryColor: Color(0xFFAF5649),
    description: "Red and gold plate with the eye slits lit. Faces forward, so it reads as a mask rather than as a head.",
  ),
  Charm(
    id: 'thorHammer',
    name: 'Thor Hammer',
    category: 'marvel',
    assetPath: 'assets/charms/Avengers/Thor Mjölnir.svg',
    metrics: CharmMetrics(mass: 3.91, radiusRatio: 0.1535, knotInset: 0.90),
    primaryColor: Color(0xFF6D828E),
    description: "Mjölnir, head square on, a rune lit on its face. The heaviest charm in the app, and on a chain it barely moves.",
  ),
  Charm(
    id: 'hulkFist',
    name: 'Hulk Fist',
    category: 'marvel',
    assetPath: 'assets/charms/Avengers/Hulk.svg',
    metrics: CharmMetrics(mass: 3.71, radiusRatio: 0.155, knotInset: 0.90),
    primaryColor: Color(0xFF30893D),
    description: "A closed green fist inside a ring. Solid, and the dullest-sounding charm here — nothing about it rings.",
  ),
  Charm(
    id: 'spiderManSwinging',
    name: 'Spider-Man Swinging',
    category: 'marvel',
    assetPath: 'assets/charms/Avengers/Spider-Man Swinging.svg',
    metrics: CharmMetrics(mass: 3.01, radiusRatio: 0.1528, knotInset: 0.90),
    primaryColor: Color(0xFF934254),
    description: "Caught mid-swing on a line he shot a moment ago, one arm up and the rest of him still travelling. The second of him in this set, and the one that looks like it is going somewhere.",
  ),
  Charm(
    id: 'batmanSymbol',
    name: 'Batman Symbol',
    category: 'dc',
    assetPath: 'assets/charms/DC/Bat-Man.svg',
    metrics: CharmMetrics(mass: 3.31, radiusRatio: 0.1575, knotInset: 0.90),
    primaryColor: Color(0xFF546077),
    description: "Wings spread wide and brushed steel-dark. The widest charm in the app, which is why it hangs at a smaller size than the rest of its set.",
  ),
  Charm(
    id: 'supermanShield',
    name: 'Superman Shield',
    category: 'dc',
    assetPath: 'assets/charms/DC/Super-Man.svg',
    metrics: CharmMetrics(mass: 3.36, radiusRatio: 0.159, knotInset: 0.90),
    primaryColor: Color(0xFF7A3526),
    description: "The crest, cut as a shield and set in silver. Red on chrome, and it catches the light from the same corner every other charm does.",
  ),
  Charm(
    id: 'wonderWomanEmblem',
    name: 'Wonder Woman Emblem',
    category: 'dc',
    assetPath: 'assets/charms/DC/Wonder Women.svg',
    metrics: CharmMetrics(mass: 3.21, radiusRatio: 0.1605, knotInset: 0.90),
    primaryColor: Color(0xFFB78960),
    description: "Gold wings folded into a W, over red and blue. Broad across the shoulders and narrow at the point, so it settles nose-down.",
  ),
  Charm(
    id: 'shazamLightning',
    name: 'Shazam Lightning',
    category: 'dc',
    assetPath: 'assets/charms/DC/Flash.svg',
    metrics: CharmMetrics(mass: 2.91, radiusRatio: 0.1485, knotInset: 0.90),
    primaryColor: Color(0xFF912619),
    description: "A single bolt in red and gold. The lightest charm in the set and the quickest to swing.",
  ),
  Charm(
    id: 'greenLanternRing',
    name: 'Green Lantern Ring',
    category: 'dc',
    assetPath: 'assets/charms/DC/Green Lantern.svg',
    metrics: CharmMetrics(mass: 3.06, radiusRatio: 0.161, knotInset: 0.90),
    primaryColor: Color(0xFF11BA66),
    description: "A lit green stone in a silver ring. The one charm in this set that glows rather than shines.",
  ),
  Charm(
    id: 'vel',
    name: 'Vel',
    category: 'tamilSpiritual',
    assetPath: 'assets/charms/Tamil Gods/Muruga Vel.svg',
    metrics: CharmMetrics(mass: 3.11, radiusRatio: 0.162, knotInset: 0.90),
    primaryColor: Color(0xFFB78E54),
    description: "Murugan's spear, and the sign of the god himself rather than a weapon he carries. A vel is planted at his hill shrines and carried by pilgrims at Thaipusam; the leaf-shaped blade is read as wisdom, broad at the base and sharp at the point.",
  ),
  Charm(
    id: 'vinayagarCoin',
    name: 'Vinayagar Coin',
    category: 'tamilSpiritual',
    assetPath: 'assets/charms/Tamil Gods/Vinayaga.svg',
    metrics: CharmMetrics(mass: 3.16, radiusRatio: 0.1468, knotInset: 0.90),
    primaryColor: Color(0xFFB58949),
    description: "Vinayagar — Ganesha — struck in relief inside a wreath. He is asked first, before any journey, any examination and any new venture, because he is the one who removes what is in the way.",
  ),
  Charm(
    id: 'omSymbol',
    name: 'OM Symbol',
    category: 'tamilSpiritual',
    assetPath: 'assets/charms/Tamil Gods/OM.svg',
    metrics: CharmMetrics(mass: 2.97, radiusRatio: 0.163, knotInset: 0.90),
    primaryColor: Color(0xFFAA6D54),
    description: "The Om, set in gold and stoned in red and green. It opens a prayer and closes one, and is cut above doorways so that the sound is there whether or not anyone is saying it.",
  ),
  Charm(
    id: 'karuppuStatue',
    name: 'Karuppu Statue',
    category: 'tamilSpiritual',
    assetPath: 'assets/charms/Tamil Gods/Karuppu.svg',
    metrics: CharmMetrics(mass: 3.61, radiusRatio: 0.1635, knotInset: 0.90),
    primaryColor: Color(0xFF82604C),
    description: "Karuppasamy, a guardian deity of the village boundary, cast dark and standing with his aruval raised. He is set at the edge of a settlement facing outward: the one who keeps watch on what a house cannot see.",
  ),
  Charm(
    id: 'templeBell',
    name: 'Temple Bell',
    category: 'tamilSpiritual',
    assetPath: 'assets/charms/Tamil Gods/Mani.svg',
    metrics: CharmMetrics(mass: 3.41, radiusRatio: 0.1645, knotInset: 0.90),
    primaryColor: Color(0xFFA37751),
    description: "The mani, rung on the way in and not on the way out. The note is meant to clear the mind of whatever it walked in carrying, so that what happens next is the only thing in it.",
  ),
  Charm(
    id: 'btsMemberOne',
    name: 'RM',
    category: 'bts',
    assetPath: 'assets/charms/BTS/RM.svg',
    metrics: CharmMetrics(mass: 2.65, radiusRatio: 0.1593, knotInset: 0.90),
    primaryColor: Color(0xFF8756A0),
    description: "Namjoon — RM, the leader, and the one who speaks for the seven when there is speaking to be done.",
  ),
  Charm(
    id: 'btsMemberTwo',
    name: 'Jin',
    category: 'bts',
    assetPath: 'assets/charms/BTS/Jin.svg',
    metrics: CharmMetrics(mass: 2.68, radiusRatio: 0.1601, knotInset: 0.90),
    primaryColor: Color(0xFFA87F68),
    description: "Seokjin — Jin, the eldest, and by his own long-running claim worldwide handsome.",
  ),
  Charm(
    id: 'btsMemberThree',
    name: 'SUGA',
    category: 'bts',
    assetPath: 'assets/charms/BTS/SUGA.svg',
    metrics: CharmMetrics(mass: 2.71, radiusRatio: 0.1609, knotInset: 0.90),
    primaryColor: Color(0xFFBA8C87),
    description: "Yoongi — SUGA, who produces as Agust D and says the least of the seven on stage.",
  ),
  Charm(
    id: 'btsMemberFour',
    name: 'j-hope',
    category: 'bts',
    assetPath: 'assets/charms/BTS/j-hope.svg',
    metrics: CharmMetrics(mass: 2.74, radiusRatio: 0.1617, knotInset: 0.90),
    primaryColor: Color(0xFF70637A),
    description: "Hoseok — j-hope, the dancer of the group, and the one the others call their sunshine.",
  ),
  Charm(
    id: 'btsMemberFive',
    name: 'Jimin',
    category: 'bts',
    assetPath: 'assets/charms/BTS/Jimin.svg',
    metrics: CharmMetrics(mass: 2.77, radiusRatio: 0.1625, knotInset: 0.90),
    primaryColor: Color(0xFF8449AA),
    description: "Jimin — the smallest of the seven and the one trained in contemporary dance before any of this.",
  ),
  Charm(
    id: 'btsMemberSix',
    name: 'V',
    category: 'bts',
    assetPath: 'assets/charms/BTS/V.svg',
    metrics: CharmMetrics(mass: 2.8, radiusRatio: 0.1633, knotInset: 0.90),
    primaryColor: Color(0xFFB27554),
    description: "Taehyung — V, the baritone, and the one who named himself after a letter.",
  ),
  Charm(
    id: 'btsMemberSeven',
    name: 'Jungkook',
    category: 'bts',
    assetPath: 'assets/charms/BTS/Jungkook.svg',
    metrics: CharmMetrics(mass: 2.83, radiusRatio: 0.1641, knotInset: 0.90),
    primaryColor: Color(0xFF8C59AA),
    description: "Jungkook — the maknae, the youngest, and the one who joined at fifteen.",
  ),
  Charm(
    id: 'ronaldoJersey',
    name: 'Ronaldo 7',
    category: 'footballLegends',
    assetPath: 'assets/charms/Football/Ronaldo 7.svg',
    metrics: CharmMetrics(mass: 3.02, radiusRatio: 0.1652, knotInset: 0.90),
    primaryColor: Color(0xFF930F16),
    description: "Portugal's number seven, in the maroon and gold of the home shirt. The seven is the only number in this set that has become a name.",
  ),
  Charm(
    id: 'messiJersey',
    name: 'Messi 10',
    category: 'footballLegends',
    assetPath: 'assets/charms/Football/Messi 10.svg',
    metrics: CharmMetrics(mass: 3.08, radiusRatio: 0.1656, knotInset: 0.90),
    primaryColor: Color(0xFF5993B7),
    description: "Argentina's sky blue and white stripes with the ten on the back — the shirt a World Cup was finally won in.",
  ),
  Charm(
    id: 'neymarJersey',
    name: 'Neymar 10',
    category: 'footballLegends',
    assetPath: 'assets/charms/Football/Neymar 10.svg',
    metrics: CharmMetrics(mass: 3.13, radiusRatio: 0.166, knotInset: 0.90),
    primaryColor: Color(0xFFDDB505),
    description: "Brazil's canarinho yellow, green at the collar and cuffs, ten on the back.",
  ),
  Charm(
    id: 'realMadridCrest',
    name: 'Real Madrid',
    category: 'footballLegends',
    assetPath: 'assets/charms/Football/Real Madrid.svg',
    metrics: CharmMetrics(mass: 3.18, radiusRatio: 0.1664, knotInset: 0.90),
    primaryColor: Color(0xFFB5874F),
    description: "The C, F and M interlocked under a royal crown — granted by Alfonso XIII in 1920, which is where the Real comes from.",
  ),
  Charm(
    id: 'fcBarcelonaCrest',
    name: 'FC Barcelona',
    category: 'footballLegends',
    assetPath: 'assets/charms/Football/FC Barcelona.svg',
    metrics: CharmMetrics(mass: 3.23, radiusRatio: 0.1668, knotInset: 0.90),
    primaryColor: Color(0xFF752649),
    description: "Blaugrana: the St George's cross and the Catalan bars above, the blue and claret halves below, a ball at the foot.",
  ),
  Charm(
    id: 'billieEilish',
    name: 'Billie Eilish',
    category: 'musicLegends',
    assetPath: 'assets/charms/Music/Billie Eilish.svg',
    metrics: CharmMetrics(mass: 2.62, radiusRatio: 0.1672, knotInset: 0.90),
    primaryColor: Color(0xFFA39E5E),
    description: "Green roots over black, sat down in oversized everything, looking like she would rather not be photographed.",
  ),
  Charm(
    id: 'xxxtentacion',
    name: 'XXXTentacion',
    category: 'musicLegends',
    assetPath: 'assets/charms/Music/XXXTentacion.svg',
    metrics: CharmMetrics(mass: 2.67, radiusRatio: 0.1676, knotInset: 0.90),
    primaryColor: Color(0xFFA87C56),
    description: "Half-blond dreads and folded arms, sitting the way the album covers had him sit.",
  ),
  Charm(
    id: 'michaelJackson',
    name: 'Michael Jackson',
    category: 'musicLegends',
    assetPath: 'assets/charms/Music/Michael Jackson.svg',
    metrics: CharmMetrics(mass: 2.72, radiusRatio: 0.168, knotInset: 0.90),
    primaryColor: Color(0xFF8C4C3D),
    description: "Caught mid-lean with the fedora down and one sequinned glove up — the pose that needs no caption anywhere on earth.",
  ),
  Charm(
    id: 'taylorSwift',
    name: 'Taylor Swift',
    category: 'musicLegends',
    assetPath: 'assets/charms/Music/Taylor Swift.svg',
    metrics: CharmMetrics(mass: 2.78, radiusRatio: 0.1684, knotInset: 0.90),
    primaryColor: Color(0xFFB58463),
    description: "Sat on a flight case with an acoustic, which is where the songs start before a stadium gets involved.",
  ),
  Charm(
    id: 'juiceWrld',
    name: 'Juice WRLD',
    category: 'musicLegends',
    assetPath: 'assets/charms/Music/Juice WRLD.svg',
    metrics: CharmMetrics(mass: 2.84, radiusRatio: 0.1688, knotInset: 0.90),
    primaryColor: Color(0xFF82563D),
    description: "999 across the hoodie — his own number, six-six-six turned over, for taking a bad thing and making something of it.",
  ),
  Charm(
    id: 'theWeeknd',
    name: 'The Weeknd',
    category: 'musicLegends',
    assetPath: 'assets/charms/Music/The Weeknd.svg',
    metrics: CharmMetrics(mass: 2.89, radiusRatio: 0.1694, knotInset: 0.90),
    primaryColor: Color(0xFF9B423D),
    description: "Sequined red jacket over black, arms out and eyes shut, halfway through the note that made the night famous.",
  ),
  Charm(
    id: 'rachelGreen',
    name: 'Rachel Green',
    category: 'friends',
    assetPath: 'assets/charms/Friends/Rachel Green.svg',
    metrics: CharmMetrics(mass: 2.87, radiusRatio: 0.1692, knotInset: 0.90),
    primaryColor: Color(0xFFA37051),
    description: "Coffee in hand, bag on the shoulder — which is how she spent a decent fraction of ten years.",
  ),
  Charm(
    id: 'monicaGeller',
    name: 'Monica Geller',
    category: 'friends',
    assetPath: 'assets/charms/Friends/Monica Geller.svg',
    metrics: CharmMetrics(mass: 2.92, radiusRatio: 0.1696, knotInset: 0.90),
    primaryColor: Color(0xFFA8775E),
    description: "Arms folded, all in black, and everything behind her exactly where it ought to be.",
  ),
  Charm(
    id: 'rossGeller',
    name: 'Ross Geller',
    category: 'friends',
    assetPath: 'assets/charms/Friends/Ross Geller.svg',
    metrics: CharmMetrics(mass: 2.98, radiusRatio: 0.1702, knotInset: 0.90),
    primaryColor: Color(0xFFA57559),
    description: "Holding a dinosaur, because he is a palaeontologist and would like a moment of your time to explain it.",
  ),
  Charm(
    id: 'joeyTribbiani',
    name: 'Joey Tribbiani',
    category: 'friends',
    assetPath: 'assets/charms/Friends/Joey Tribbiani.svg',
    metrics: CharmMetrics(mass: 3.03, radiusRatio: 0.1706, knotInset: 0.90),
    primaryColor: Color(0xFFA37054),
    description: "Leather jacket, finger up, mouth open. You already know the line.",
  ),
  Charm(
    id: 'chandlerBing',
    name: 'Chandler Bing',
    category: 'friends',
    assetPath: 'assets/charms/Friends/Chandler Bing.svg',
    metrics: CharmMetrics(mass: 3.09, radiusRatio: 0.171, knotInset: 0.90),
    primaryColor: Color(0xFF9B6D56),
    description: "In the suit, hands in pockets, mid-sarcasm. Could his job BE any harder to describe?",
  ),
  Charm(
    id: 'phoebeBuffay',
    name: 'Phoebe Buffay',
    category: 'friends',
    assetPath: 'assets/charms/Friends/Phoebe Buffay.svg',
    metrics: CharmMetrics(mass: 3.14, radiusRatio: 0.1714, knotInset: 0.90),
    primaryColor: Color(0xFFAD7242),
    description: "Guitar in hand, which means a cat somewhere is about to be sung about at length.",
  ),
  Charm(
    id: 'walterWhite',
    name: 'Walter White',
    category: 'breakingBad',
    assetPath: 'assets/charms/Breaking Bad/Walter White.svg',
    metrics: CharmMetrics(mass: 3.28, radiusRatio: 0.1718, knotInset: 0.90),
    primaryColor: Color(0xFFC68E23),
    description: "Yellow hazmat, a flask of blue in one hand and the gas mask in the other. Still telling himself it is about the family.",
  ),
  Charm(
    id: 'jessePinkman',
    name: 'Jesse Pinkman',
    category: 'breakingBad',
    assetPath: 'assets/charms/Breaking Bad/Jesse Pinkman.svg',
    metrics: CharmMetrics(mass: 3.33, radiusRatio: 0.1722, knotInset: 0.90),
    primaryColor: Color(0xFFBC821C),
    description: "Beanie and a yellow jacket, standing like a man who has just been told off and is about to be told off again.",
  ),
  Charm(
    id: 'saulGoodman',
    name: 'Saul Goodman',
    category: 'breakingBad',
    assetPath: 'assets/charms/Breaking Bad/Saul Goodman.svg',
    metrics: CharmMetrics(mass: 3.38, radiusRatio: 0.1726, knotInset: 0.90),
    primaryColor: Color(0xFFC19156),
    description: "Pinstripes, a loud tie and a sign carrying his own catchphrase, which is the most honest thing about him.",
  ),
  Charm(
    id: 'gusFring',
    name: 'Gus Fring',
    category: 'breakingBad',
    assetPath: 'assets/charms/Breaking Bad/Gus Fring.svg',
    metrics: CharmMetrics(mass: 3.43, radiusRatio: 0.173, knotInset: 0.90),
    primaryColor: Color(0xFF895435),
    description: "The good suit, the glasses, and absolutely nothing showing on his face. That is the frightening part.",
  ),
  Charm(
    id: 'mikeEhrmantraut',
    name: 'Mike Ehrmantraut',
    category: 'breakingBad',
    assetPath: 'assets/charms/Breaking Bad/Mike Ehrmantraut.svg',
    metrics: CharmMetrics(mass: 3.48, radiusRatio: 0.1734, knotInset: 0.90),
    primaryColor: Color(0xFFB2775B),
    description: "Leather jacket, hands where you can see them, and a patience you would be unwise to test.",
  ),
  Charm(
    id: 'heisenberg',
    name: 'Heisenberg',
    category: 'breakingBad',
    assetPath: 'assets/charms/Breaking Bad/Heisenberg.svg',
    metrics: CharmMetrics(mass: 3.53, radiusRatio: 0.1738, knotInset: 0.90),
    primaryColor: Color(0xFF776351),
    description: "The porkpie hat, the glasses, a bag in one hand and the product in the other. The same man as the hazmat, further along.",
  ),
  Charm(
    id: 'rv',
    name: 'RV',
    category: 'breakingBad',
    assetPath: 'assets/charms/Breaking Bad/RV.svg',
    metrics: CharmMetrics(mass: 3.58, radiusRatio: 0.1766, knotInset: 0.90),
    primaryColor: Color(0xFFCEA366),
    description: "The Fleetwood Bounder, sun-bleached and desert-dented, that did the cooking before anybody had a laboratory. The most recognisable vehicle on television.",
  ),
  Charm(
    id: 'eleven',
    name: 'Eleven',
    category: 'strangerThings',
    assetPath: 'assets/charms/Stranger Things/Eleven.svg',
    metrics: CharmMetrics(mass: 2.24, radiusRatio: 0.1742, knotInset: 0.90),
    primaryColor: Color(0xFFAF7256),
    description: "Pink dress, buzzed hair, one hand out. The nosebleed comes after.",
  ),
  Charm(
    id: 'mikeWheeler',
    name: 'Mike Wheeler',
    category: 'strangerThings',
    assetPath: 'assets/charms/Stranger Things/Mike Wheeler.svg',
    metrics: CharmMetrics(mass: 2.28, radiusRatio: 0.1746, knotInset: 0.90),
    primaryColor: Color(0xFF9B6B51),
    description: "Walkie-talkie up, waiting on a reply from someone who may not be able to answer.",
  ),
  Charm(
    id: 'dustinHenderson',
    name: 'Dustin Henderson',
    category: 'strangerThings',
    assetPath: 'assets/charms/Stranger Things/Dustin Henderson.svg',
    metrics: CharmMetrics(mass: 2.33, radiusRatio: 0.175, knotInset: 0.90),
    primaryColor: Color(0xFFA56D4F),
    description: "Cap on, headset on, halfway through a sentence and not slowing down for anybody.",
  ),
  Charm(
    id: 'lucasSinclair',
    name: 'Lucas Sinclair',
    category: 'strangerThings',
    assetPath: 'assets/charms/Stranger Things/Lucas Sinclair.svg',
    metrics: CharmMetrics(mass: 2.38, radiusRatio: 0.1754, knotInset: 0.90),
    primaryColor: Color(0xFF7A4226),
    description: "Camo bandana and a wrist-rocket, drawn and aimed. The only one of them who came prepared.",
  ),
  Charm(
    id: 'willByers',
    name: 'Will Byers',
    category: 'strangerThings',
    assetPath: 'assets/charms/Stranger Things/Will Byers.svg',
    metrics: CharmMetrics(mass: 2.44, radiusRatio: 0.1758, knotInset: 0.90),
    primaryColor: Color(0xFFA56B3A),
    description: "Holding the string of Christmas lights his mother nailed to the wall to spell things out, letter by letter.",
  ),
  Charm(
    id: 'demogorgon',
    name: 'Demogorgon',
    category: 'strangerThings',
    assetPath: 'assets/charms/Stranger Things/Demogorgon.svg',
    metrics: CharmMetrics(mass: 2.48, radiusRatio: 0.1762, knotInset: 0.90),
    primaryColor: Color(0xFF913D30),
    description: "The face opens into five petals. That is the whole of what anybody needs to know about it.",
  ),
  Charm(
    id: 'circle',
    name: 'Bead',
    category: 'classic',
    assetPath: 'assets/charms/Bead.svg',
    metrics: CharmMetrics(mass: 2.6, radiusRatio: 0.14, knotInset: 0.90),
    primaryColor: Color(0xFF1E33A8),
    description: "A plain glass bead, the charm Hangly ships with. Simple, weighty and never out of place.",
  ),
  Charm(
    id: 'camera',
    name: 'Camera',
    category: 'classic',
    assetPath: 'assets/charms/Camera.svg',
    metrics: CharmMetrics(mass: 4.2, radiusRatio: 0.17, knotInset: 0.90),
    primaryColor: Color(0xFF5B606D),
    description: "For photographers and the perpetually nostalgic. The heaviest charm in the box.",
  ),
  Charm(
    id: 'star',
    name: 'Star',
    category: 'classic',
    assetPath: 'assets/charms/Star.svg',
    metrics: CharmMetrics(mass: 2.2, radiusRatio: 0.157, knotInset: 0.90),
    primaryColor: Color(0xFFFFC63F),
    description: "Everyone's first lucky charm. The lightest in the set, so it swings the fastest.",
  ),
  Charm(
    id: 'heart',
    name: 'Heart',
    category: 'classic',
    assetPath: 'assets/charms/Heart.svg',
    metrics: CharmMetrics(mass: 2.9, radiusRatio: 0.149, knotInset: 0.90),
    primaryColor: Color(0xFFEDB2BC),
    description: "Worn on the sleeve, or in this case at the top of the screen.",
  ),
  Charm(
    id: 'diamond',
    name: 'Diamond',
    category: 'classic',
    assetPath: 'assets/charms/Diamond.svg',
    metrics: CharmMetrics(mass: 3.4, radiusRatio: 0.142, knotInset: 0.90),
    primaryColor: Color(0xFF9EE0F7),
    description: "Cut, faceted and indestructible. Heavy enough to hang the rope nearly straight.",
  ),
];

  static Charm byId(String id) {
    return all.firstWhere((c) => c.id == id, orElse: () => defaultCharm);
  }

  static List<Charm> byCategory(String category) {
    if (category == 'all') return all;
    return all.where((c) => c.category == category).toList();
  }

  static List<Charm> search(String query) {
    if (query.trim().isEmpty) return all;
    final q = query.toLowerCase().trim();
    return all.where((c) =>
        c.name.toLowerCase().contains(q) ||
        c.description.toLowerCase().contains(q) ||
        c.category.toLowerCase().contains(q)).toList();
  }
}
