//
//  CharmCatalog.Generated.cs
//  Hangly
//
//  GENERATED FILE — DO NOT EDIT.
//
//  Written by tools/generate-catalogue.py from reference/swift/. Eighty-one
//  entries of pure data, read out of the Swift rather than typed again, because
//  a mistyped mass is a bug no compiler sees and only a screenshot catches.
//
//  To change a charm, change the Swift and re-run the generator.
//

namespace Hangly.Core.Models;

public static partial class CharmCatalog
{
    /// <summary>The Library's categories, in the order the chips offer them.</summary>
    public static IReadOnlyList<CharmCategory> Categories { get; } =
    [
        new("protection", "Protection"),
        new("luck", "Luck & Fortune"),
        new("ritual", "Ritual & Home"),
        new("classic", "Classic"),
        new("marvel", "Marvel"),
        new("dc", "DC"),
        new("tamilSpiritual", "Tamil Spiritual"),
        new("bts", "BTS"),
        new("footballLegends", "Football Legends"),
        new("musicLegends", "Music Legends"),
        new("friends", "Friends"),
        new("breakingBad", "Breaking Bad"),
        new("strangerThings", "Stranger Things"),
    ];

    /// <summary>The collections the Library offers as cards, in catalogue order.</summary>
    /// <remarks>
    /// A collection is a category that has a line written about it. The ones without
    /// — protection, luck, ritual, classic — are filters rather than collections and
    /// are offered as chips only, which is how macOS presents them.
    /// </remarks>
    public static IReadOnlyList<CharmCollection> Collections { get; } =
    [
        new("marvel", "Marvel", "Iconic Marvel-inspired charms designed as hanging ornaments."),
        new("dc", "DC", "Legendary DC-inspired symbols reimagined as hanging charms."),
        new("tamilSpiritual", "Tamil Spiritual", "Traditional Tamil spiritual symbols and guardian deities."),
        new("bts", "BTS", "Stylized BTS-inspired collectible hanging charms."),
        new("footballLegends", "Football Legends", "Icons of world football."),
        new("musicLegends", "Music Legends", "Artists who shaped modern music."),
        new("friends", "Friends", "The iconic friends from New York."),
        new("breakingBad", "Breaking Bad", "The legendary Breaking Bad universe."),
        new("strangerThings", "Stranger Things", "Mysteries from the Upside Down."),
    ];

    /// <summary>Every built-in charm, in the order the charm menu offers them.</summary>
    public static IReadOnlyList<CharmCatalogEntry> All { get; } =
    [
        new(
            Id: "nazar",
            DisplayName: "Nazar boncuğu",
            FileName: "Nazar Boncuğu.svg",
            Mass: 2.75,
            RadiusRatio: 0.145,
            Palette: new CharmPalette(
                new CharmColor(0.10, 0.22, 0.68),
                new CharmColor(0.06, 0.12, 0.42),
                new CharmColor(0.03, 0.06, 0.25),
                new CharmColor(0.42, 0.58, 0.95)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "protection",
            Region: "Turkey and the Mediterranean",
            Description: "A glass eye bead hung to deflect the evil eye, the envious glance believed to bring misfortune. Found across Turkey, Greece and the wider Mediterranean, on doorways, cradles and dashboards alike.",
            Tags: ["evil eye", "glass", "blue", "amulet", "Turkey", "Greece"]),
        new(
            Id: "hamsa",
            DisplayName: "Hamsa",
            FileName: "Hamsa.svg",
            Mass: 3.05,
            RadiusRatio: 0.158,
            Palette: new CharmPalette(
                new CharmColor(0.15, 0.24, 0.60),
                new CharmColor(0.09, 0.14, 0.42),
                new CharmColor(0.05, 0.08, 0.26),
                new CharmColor(0.50, 0.62, 0.95)),
            BeadCount: 2,
            BodyRun: 2,
            CategoryId: "protection",
            Region: "Middle East and North Africa",
            Description: "An open right hand, often with an eye in the palm, carried as protection against harm. Shared by Jewish, Muslim and Christian communities from Morocco to the Levant.",
            Tags: ["hand", "eye", "amulet", "Fatima", "Miriam"]),
        new(
            Id: "nimbuMirchi",
            DisplayName: "Nimbu-mirchi",
            FileName: "Nimbu-mirchi.svg",
            Mass: 2.85,
            RadiusRatio: 0.152,
            Palette: new CharmPalette(
                new CharmColor(0.98, 0.84, 0.18),
                new CharmColor(0.85, 0.62, 0.08),
                new CharmColor(0.55, 0.38, 0.03),
                new CharmColor(1.00, 0.96, 0.62)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "protection",
            Region: "India",
            Description: "A lemon and green chillies strung together and hung at shop doors and on vehicles across India to ward off the evil eye, and to give bad luck something sour to chew on instead.",
            Tags: ["lemon", "chilli", "evil eye", "doorway", "totka"]),
        new(
            Id: "ghanta",
            DisplayName: "Ghanta",
            FileName: "Ghanta.svg",
            Mass: 4.05,
            RadiusRatio: 0.15,
            Palette: new CharmPalette(
                new CharmColor(0.76, 0.45, 0.22),
                new CharmColor(0.55, 0.30, 0.13),
                new CharmColor(0.32, 0.17, 0.07),
                new CharmColor(0.98, 0.78, 0.55)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "ritual",
            Region: "India",
            Description: "The temple bell of Hindu and Buddhist worship. Its ring is said to clear the mind of the person who strikes it and to announce their arrival to the divine.",
            Tags: ["bell", "temple", "copper", "puja", "sound"]),
        new(
            Id: "drishtiBommai",
            DisplayName: "Drishti bommai",
            FileName: "Dhrishti bomma.svg",
            Mass: 3.25,
            RadiusRatio: 0.164,
            Palette: new CharmPalette(
                new CharmColor(0.86, 0.14, 0.12),
                new CharmColor(0.62, 0.08, 0.08),
                new CharmColor(0.36, 0.04, 0.05),
                new CharmColor(1.00, 0.55, 0.45)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "protection",
            Region: "South India",
            Description: "A fierce painted face hung outside homes and building sites in Tamil Nadu. Its job is to draw the evil eye onto itself and away from whatever it guards.",
            Tags: ["mask", "demon", "evil eye", "Tamil Nadu", "guardian"]),
        new(
            Id: "panchangJie",
            DisplayName: "Pánchángjié",
            FileName: "Pánchang Jié.svg",
            Mass: 2.45,
            RadiusRatio: 0.16,
            Palette: new CharmPalette(
                new CharmColor(0.88, 0.14, 0.18),
                new CharmColor(0.62, 0.08, 0.10),
                new CharmColor(0.36, 0.04, 0.06),
                new CharmColor(1.00, 0.62, 0.60)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "luck",
            Region: "China",
            Description: "The endless knot, tied from a single red cord with no beginning and no end. A symbol of longevity, unity and good fortune, hung at Lunar New Year.",
            Tags: ["knot", "red", "tassel", "New Year", "longevity", "Chinese knot"]),
        new(
            Id: "daruma",
            DisplayName: "Daruma",
            FileName: "Daruma.svg",
            Mass: 3.65,
            RadiusRatio: 0.154,
            Palette: new CharmPalette(
                new CharmColor(0.88, 0.12, 0.12),
                new CharmColor(0.62, 0.06, 0.06),
                new CharmColor(0.38, 0.03, 0.03),
                new CharmColor(1.00, 0.50, 0.40)),
            BeadCount: 3,
            BodyRun: 3,
            CategoryId: "luck",
            Region: "Japan",
            Description: "A round, weighted doll modelled on the monk Bodhidharma. You paint one eye while making a wish and the other when it comes true, and it always rights itself when knocked over.",
            Tags: ["doll", "wish", "perseverance", "red", "Bodhidharma"]),
        new(
            Id: "manekiNeko",
            DisplayName: "Maneki-neko",
            FileName: "Maneki-neko.svg",
            Mass: 3.45,
            RadiusRatio: 0.167,
            Palette: new CharmPalette(
                new CharmColor(0.97, 0.95, 0.90),
                new CharmColor(0.82, 0.78, 0.70),
                new CharmColor(0.55, 0.50, 0.42),
                new CharmColor(1.00, 1.00, 1.00)),
            BeadCount: 4,
            BodyRun: 4,
            CategoryId: "luck",
            Region: "Japan",
            Description: "The beckoning cat, raised paw inviting good fortune through the door. A raised right paw is said to bring money; a raised left paw brings customers.",
            Tags: ["cat", "beckoning", "calico", "shop", "fortune"]),
        new(
            Id: "horseshoe",
            DisplayName: "Horseshoe",
            FileName: "Horseshoe.svg",
            Mass: 3.85,
            RadiusRatio: 0.151,
            Palette: new CharmPalette(
                new CharmColor(0.58, 0.60, 0.64),
                new CharmColor(0.38, 0.40, 0.44),
                new CharmColor(0.20, 0.21, 0.24),
                new CharmColor(0.88, 0.90, 0.93)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "luck",
            Region: "Europe and the Americas",
            Description: "Iron shaped by fire, nailed above a door for luck. Hung open end up it holds the luck in; open end down it pours the luck over those who pass beneath.",
            Tags: ["iron", "door", "luck", "seven nails", "blacksmith"]),
        new(
            Id: "scarab",
            DisplayName: "Scarab",
            FileName: "Scarab.svg",
            Mass: 3.15,
            RadiusRatio: 0.146,
            Palette: new CharmPalette(
                new CharmColor(0.20, 0.74, 0.76),
                new CharmColor(0.10, 0.50, 0.55),
                new CharmColor(0.05, 0.30, 0.34),
                new CharmColor(0.70, 0.95, 0.94)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "protection",
            Region: "Ancient Egypt",
            Description: "The dung beetle, sacred to the sun's rebirth each morning as it rolls its ball across the sky. Worn as an amulet in ancient Egypt for protection and renewal.",
            Tags: ["beetle", "Egypt", "turquoise", "rebirth", "amulet", "sun"]),
        new(
            Id: "himmeli",
            DisplayName: "Himmeli",
            FileName: "Himmeli.svg",
            Mass: 2.35,
            RadiusRatio: 0.169,
            Palette: new CharmPalette(
                new CharmColor(0.82, 0.64, 0.26),
                new CharmColor(0.60, 0.44, 0.14),
                new CharmColor(0.36, 0.26, 0.07),
                new CharmColor(0.99, 0.90, 0.60)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "ritual",
            Region: "Finland",
            Description: "A geometric mobile of rye straw hung above the table at midwinter in Finland to bless the coming harvest. The name comes from the Swedish word for sky.",
            Tags: ["straw", "geometric", "mobile", "midwinter", "harvest", "gold"]),
        new(
            Id: "dreamCatcher",
            DisplayName: "Dream Catcher",
            FileName: "Dream Catcher.svg",
            Mass: 2.52,
            RadiusRatio: 0.1686,
            Palette: new CharmPalette(
                new CharmColor(0.62, 0.49, 0.32),
                new CharmColor(0.38, 0.30, 0.20),
                new CharmColor(0.07, 0.03, 0.01),
                new CharmColor(0.84, 0.75, 0.63)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "protection",
            Region: "North America",
            Description: "An Ojibwe hoop webbed like a spider's, hung over a sleeping child so the bad dreams catch in the net and the good ones slip through the middle and down the feathers.",
            Tags: ["dream catcher", "Ojibwe", "feathers", "web", "sleep", "protection"]),
        new(
            Id: "spiderMan",
            DisplayName: "Spider-Man",
            FileName: "Avengers/Spider-Man.svg",
            Mass: 2.96,
            RadiusRatio: 0.1525,
            Palette: new CharmPalette(
                new CharmColor(0.53, 0.17, 0.26),
                new CharmColor(0.33, 0.11, 0.16),
                new CharmColor(0.05, 0.04, 0.11),
                new CharmColor(0.61, 0.50, 0.58)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "marvel",
            Region: "Marvel",
            Description: "Hanging head-down from a thread of his own, which is the way he is most often drawn and the only pose in this set that was already a charm before anybody hung it. Pair him with Spider Thread.",
            Tags: ["Spider-Man", "web", "upside down", "Marvel"]),
        new(
            Id: "captainAmericaShield",
            DisplayName: "Captain America Shield",
            FileName: "Avengers/Captain-America.svg",
            Mass: 3.46,
            RadiusRatio: 0.1515,
            Palette: new CharmPalette(
                new CharmColor(0.70, 0.13, 0.17),
                new CharmColor(0.43, 0.08, 0.11),
                new CharmColor(0.09, 0.04, 0.09),
                new CharmColor(0.73, 0.74, 0.74)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "marvel",
            Region: "Marvel",
            Description: "Concentric rings and a white star, struck face on. The heaviest thing in the set after the hammer, and it hangs like it.",
            Tags: ["Captain America", "shield", "star", "Marvel"]),
        new(
            Id: "ironManHelmet",
            DisplayName: "Iron Man Helmet",
            FileName: "Avengers/Iron-Man.svg",
            Mass: 3.26,
            RadiusRatio: 0.1495,
            Palette: new CharmPalette(
                new CharmColor(0.69, 0.34, 0.29),
                new CharmColor(0.43, 0.21, 0.18),
                new CharmColor(0.16, 0.03, 0.04),
                new CharmColor(0.98, 0.92, 0.87)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "marvel",
            Region: "Marvel",
            Description: "Red and gold plate with the eye slits lit. Faces forward, so it reads as a mask rather than as a head.",
            Tags: ["Iron Man", "helmet", "gold", "Marvel"]),
        new(
            Id: "thorHammer",
            DisplayName: "Thor Hammer",
            FileName: "Avengers/Thor Mjölnir.svg",
            Mass: 3.91,
            RadiusRatio: 0.1535,
            Palette: new CharmPalette(
                new CharmColor(0.43, 0.51, 0.56),
                new CharmColor(0.26, 0.32, 0.34),
                new CharmColor(0.11, 0.12, 0.14),
                new CharmColor(0.85, 0.88, 0.88)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "marvel",
            Region: "Marvel",
            Description: "Mjölnir, head square on, a rune lit on its face. The heaviest charm in the app, and on a chain it barely moves.",
            Tags: ["Thor", "Mjölnir", "hammer", "Marvel"]),
        new(
            Id: "hulkFist",
            DisplayName: "Hulk Fist",
            FileName: "Avengers/Hulk.svg",
            Mass: 3.71,
            RadiusRatio: 0.1550,
            Palette: new CharmPalette(
                new CharmColor(0.19, 0.54, 0.24),
                new CharmColor(0.12, 0.34, 0.15),
                new CharmColor(0.06, 0.09, 0.06),
                new CharmColor(0.39, 0.63, 0.42)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "marvel",
            Region: "Marvel",
            Description: "A closed green fist inside a ring. Solid, and the dullest-sounding charm here — nothing about it rings.",
            Tags: ["Hulk", "fist", "green", "Marvel"]),
        new(
            Id: "spiderManSwinging",
            DisplayName: "Spider-Man Swinging",
            FileName: "Avengers/Spider-Man Swinging.svg",
            Mass: 3.01,
            RadiusRatio: 0.1528,
            Palette: new CharmPalette(
                new CharmColor(0.58, 0.26, 0.33),
                new CharmColor(0.36, 0.16, 0.20),
                new CharmColor(0.07, 0.04, 0.08),
                new CharmColor(0.67, 0.54, 0.56)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "marvel",
            Region: "Marvel",
            Description: "Caught mid-swing on a line he shot a moment ago, one arm up and the rest of him still travelling. The second of him in this set, and the one that looks like it is going somewhere.",
            Tags: ["Spider-Man", "web", "swing", "Marvel"]),
        new(
            Id: "batmanSymbol",
            DisplayName: "Batman Symbol",
            FileName: "DC/Bat-Man.svg",
            Mass: 3.31,
            RadiusRatio: 0.1575,
            Palette: new CharmPalette(
                new CharmColor(0.33, 0.38, 0.47),
                new CharmColor(0.20, 0.23, 0.29),
                new CharmColor(0.04, 0.05, 0.06),
                new CharmColor(0.64, 0.61, 0.59)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "dc",
            Region: "DC",
            Description: "Wings spread wide and brushed steel-dark. The widest charm in the app, which is why it hangs at a smaller size than the rest of its set.",
            Tags: ["Batman", "bat", "wings", "DC"]),
        new(
            Id: "supermanShield",
            DisplayName: "Superman Shield",
            FileName: "DC/Super-Man.svg",
            Mass: 3.36,
            RadiusRatio: 0.1590,
            Palette: new CharmPalette(
                new CharmColor(0.48, 0.21, 0.15),
                new CharmColor(0.30, 0.13, 0.10),
                new CharmColor(0.17, 0.01, 0.01),
                new CharmColor(0.85, 0.81, 0.76)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "dc",
            Region: "DC",
            Description: "The crest, cut as a shield and set in silver. Red on chrome, and it catches the light from the same corner every other charm does.",
            Tags: ["Superman", "shield", "crest", "DC"]),
        new(
            Id: "wonderWomanEmblem",
            DisplayName: "Wonder Woman Emblem",
            FileName: "DC/Wonder Women.svg",
            Mass: 3.21,
            RadiusRatio: 0.1605,
            Palette: new CharmPalette(
                new CharmColor(0.72, 0.54, 0.38),
                new CharmColor(0.45, 0.34, 0.23),
                new CharmColor(0.06, 0.02, 0.03),
                new CharmColor(0.92, 0.83, 0.66)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "dc",
            Region: "DC",
            Description: "Gold wings folded into a W, over red and blue. Broad across the shoulders and narrow at the point, so it settles nose-down.",
            Tags: ["Wonder Woman", "emblem", "gold", "DC"]),
        new(
            Id: "shazamLightning",
            DisplayName: "Shazam Lightning",
            FileName: "DC/Flash.svg",
            Mass: 2.91,
            RadiusRatio: 0.1485,
            Palette: new CharmPalette(
                new CharmColor(0.57, 0.15, 0.10),
                new CharmColor(0.35, 0.09, 0.06),
                new CharmColor(0.31, 0.03, 0.03),
                new CharmColor(0.94, 0.87, 0.70)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "dc",
            Region: "DC",
            Description: "A single bolt in red and gold. The lightest charm in the set and the quickest to swing.",
            Tags: ["Shazam", "lightning", "bolt", "DC"]),
        new(
            Id: "greenLanternRing",
            DisplayName: "Green Lantern Ring",
            FileName: "DC/Green Lantern.svg",
            Mass: 3.06,
            RadiusRatio: 0.1610,
            Palette: new CharmPalette(
                new CharmColor(0.07, 0.73, 0.40),
                new CharmColor(0.04, 0.45, 0.25),
                new CharmColor(0.08, 0.20, 0.16),
                new CharmColor(0.86, 0.92, 0.88)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "dc",
            Region: "DC",
            Description: "A lit green stone in a silver ring. The one charm in this set that glows rather than shines.",
            Tags: ["Green Lantern", "ring", "green", "DC"]),
        new(
            Id: "vel",
            DisplayName: "Vel",
            FileName: "Tamil Gods/Muruga Vel.svg",
            Mass: 3.11,
            RadiusRatio: 0.1620,
            Palette: new CharmPalette(
                new CharmColor(0.72, 0.56, 0.33),
                new CharmColor(0.44, 0.35, 0.21),
                new CharmColor(0.28, 0.16, 0.10),
                new CharmColor(0.86, 0.76, 0.54)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "tamilSpiritual",
            Region: "Tamil Nadu, South India",
            Description: "Murugan's spear, and the sign of the god himself rather than a weapon he carries. A vel is planted at his hill shrines and carried by pilgrims at Thaipusam; the leaf-shaped blade is read as wisdom, broad at the base and sharp at the point.",
            Tags: ["Murugan", "vel", "spear", "Thaipusam", "Tamil Nadu"]),
        new(
            Id: "vinayagarCoin",
            DisplayName: "Vinayagar Coin",
            FileName: "Tamil Gods/Vinayaga.svg",
            Mass: 3.16,
            RadiusRatio: 0.1468,
            Palette: new CharmPalette(
                new CharmColor(0.71, 0.54, 0.29),
                new CharmColor(0.44, 0.34, 0.18),
                new CharmColor(0.24, 0.13, 0.06),
                new CharmColor(0.79, 0.65, 0.40)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "tamilSpiritual",
            Region: "Tamil Nadu, South India",
            Description: "Vinayagar — Ganesha — struck in relief inside a wreath. He is asked first, before any journey, any examination and any new venture, because he is the one who removes what is in the way.",
            Tags: ["Vinayagar", "Ganesha", "coin", "elephant", "beginnings"]),
        new(
            Id: "omSymbol",
            DisplayName: "OM Symbol",
            FileName: "Tamil Gods/OM.svg",
            Mass: 2.97,
            RadiusRatio: 0.1630,
            Palette: new CharmPalette(
                new CharmColor(0.67, 0.43, 0.33),
                new CharmColor(0.42, 0.27, 0.20),
                new CharmColor(0.33, 0.15, 0.13),
                new CharmColor(0.98, 0.92, 0.74)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "tamilSpiritual",
            Region: "Tamil Nadu, South India",
            Description: "The Om, set in gold and stoned in red and green. It opens a prayer and closes one, and is cut above doorways so that the sound is there whether or not anyone is saying it.",
            Tags: ["Om", "syllable", "gold", "doorway", "Tamil Nadu"]),
        new(
            Id: "karuppuStatue",
            DisplayName: "Karuppu Statue",
            FileName: "Tamil Gods/Karuppu.svg",
            Mass: 3.61,
            RadiusRatio: 0.1635,
            Palette: new CharmPalette(
                new CharmColor(0.51, 0.38, 0.30),
                new CharmColor(0.32, 0.24, 0.18),
                new CharmColor(0.06, 0.05, 0.04),
                new CharmColor(0.59, 0.49, 0.43)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "tamilSpiritual",
            Region: "Tamil Nadu, South India",
            Description: "Karuppasamy, a guardian deity of the village boundary, cast dark and standing with his aruval raised. He is set at the edge of a settlement facing outward: the one who keeps watch on what a house cannot see.",
            Tags: ["Karuppasamy", "guardian", "village deity", "aruval", "boundary"]),
        new(
            Id: "templeBell",
            DisplayName: "Temple Bell",
            FileName: "Tamil Gods/Mani.svg",
            Mass: 3.41,
            RadiusRatio: 0.1645,
            Palette: new CharmPalette(
                new CharmColor(0.64, 0.47, 0.32),
                new CharmColor(0.39, 0.29, 0.20),
                new CharmColor(0.24, 0.15, 0.10),
                new CharmColor(0.78, 0.66, 0.53)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "tamilSpiritual",
            Region: "Tamil Nadu, South India",
            Description: "The mani, rung on the way in and not on the way out. The note is meant to clear the mind of whatever it walked in carrying, so that what happens next is the only thing in it.",
            Tags: ["mani", "bell", "brass", "temple", "Tamil Nadu"]),
        new(
            Id: "btsMemberOne",
            DisplayName: "RM",
            FileName: "BTS/RM.svg",
            Mass: 2.65,
            RadiusRatio: 0.1593,
            Palette: new CharmPalette(
                new CharmColor(0.53, 0.34, 0.63),
                new CharmColor(0.33, 0.21, 0.39),
                new CharmColor(0.11, 0.07, 0.14),
                new CharmColor(0.85, 0.79, 0.79)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "bts",
            Region: "BTS",
            Description: "Namjoon — RM, the leader, and the one who speaks for the seven when there is speaking to be done.",
            Tags: ["RM", "Namjoon", "leader", "BTS"]),
        new(
            Id: "btsMemberTwo",
            DisplayName: "Jin",
            FileName: "BTS/Jin.svg",
            Mass: 2.68,
            RadiusRatio: 0.1601,
            Palette: new CharmPalette(
                new CharmColor(0.66, 0.50, 0.41),
                new CharmColor(0.41, 0.31, 0.25),
                new CharmColor(0.04, 0.03, 0.04),
                new CharmColor(0.86, 0.73, 0.65)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "bts",
            Region: "BTS",
            Description: "Seokjin — Jin, the eldest, and by his own long-running claim worldwide handsome.",
            Tags: ["Jin", "Seokjin", "vocalist", "BTS"]),
        new(
            Id: "btsMemberThree",
            DisplayName: "SUGA",
            FileName: "BTS/SUGA.svg",
            Mass: 2.71,
            RadiusRatio: 0.1609,
            Palette: new CharmPalette(
                new CharmColor(0.73, 0.55, 0.53),
                new CharmColor(0.45, 0.34, 0.33),
                new CharmColor(0.55, 0.40, 0.46),
                new CharmColor(0.89, 0.83, 0.83)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "bts",
            Region: "BTS",
            Description: "Yoongi — SUGA, who produces as Agust D and says the least of the seven on stage.",
            Tags: ["SUGA", "Yoongi", "Agust D", "BTS"]),
        new(
            Id: "btsMemberFour",
            DisplayName: "j-hope",
            FileName: "BTS/j-hope.svg",
            Mass: 2.74,
            RadiusRatio: 0.1617,
            Palette: new CharmPalette(
                new CharmColor(0.44, 0.39, 0.48),
                new CharmColor(0.27, 0.24, 0.30),
                new CharmColor(0.10, 0.08, 0.11),
                new CharmColor(0.86, 0.84, 0.86)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "bts",
            Region: "BTS",
            Description: "Hoseok — j-hope, the dancer of the group, and the one the others call their sunshine.",
            Tags: ["j-hope", "Hoseok", "dance", "BTS"]),
        new(
            Id: "btsMemberFive",
            DisplayName: "Jimin",
            FileName: "BTS/Jimin.svg",
            Mass: 2.77,
            RadiusRatio: 0.1625,
            Palette: new CharmPalette(
                new CharmColor(0.52, 0.29, 0.67),
                new CharmColor(0.32, 0.18, 0.41),
                new CharmColor(0.12, 0.07, 0.18),
                new CharmColor(0.79, 0.62, 0.78)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "bts",
            Region: "BTS",
            Description: "Jimin — the smallest of the seven and the one trained in contemporary dance before any of this.",
            Tags: ["Jimin", "dance", "vocalist", "BTS"]),
        new(
            Id: "btsMemberSix",
            DisplayName: "V",
            FileName: "BTS/V.svg",
            Mass: 2.80,
            RadiusRatio: 0.1633,
            Palette: new CharmPalette(
                new CharmColor(0.70, 0.46, 0.33),
                new CharmColor(0.43, 0.29, 0.21),
                new CharmColor(0.53, 0.32, 0.23),
                new CharmColor(0.94, 0.85, 0.78)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "bts",
            Region: "BTS",
            Description: "Taehyung — V, the baritone, and the one who named himself after a letter.",
            Tags: ["V", "Taehyung", "baritone", "BTS"]),
        new(
            Id: "btsMemberSeven",
            DisplayName: "Jungkook",
            FileName: "BTS/Jungkook.svg",
            Mass: 2.83,
            RadiusRatio: 0.1641,
            Palette: new CharmPalette(
                new CharmColor(0.55, 0.35, 0.67),
                new CharmColor(0.34, 0.22, 0.42),
                new CharmColor(0.03, 0.02, 0.05),
                new CharmColor(0.87, 0.74, 0.83)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "bts",
            Region: "BTS",
            Description: "Jungkook — the maknae, the youngest, and the one who joined at fifteen.",
            Tags: ["Jungkook", "maknae", "youngest", "BTS"]),
        new(
            Id: "ronaldoJersey",
            DisplayName: "Ronaldo 7",
            FileName: "Football/Ronaldo 7.svg",
            Mass: 3.02,
            RadiusRatio: 0.1652,
            Palette: new CharmPalette(
                new CharmColor(0.58, 0.06, 0.09),
                new CharmColor(0.36, 0.03, 0.06),
                new CharmColor(0.42, 0.01, 0.03),
                new CharmColor(0.93, 0.83, 0.64)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "footballLegends",
            Region: "Portugal",
            Description: "Portugal's number seven, in the maroon and gold of the home shirt. The seven is the only number in this set that has become a name.",
            Tags: ["Ronaldo", "Portugal", "seven", "jersey"]),
        new(
            Id: "messiJersey",
            DisplayName: "Messi 10",
            FileName: "Football/Messi 10.svg",
            Mass: 3.08,
            RadiusRatio: 0.1656,
            Palette: new CharmPalette(
                new CharmColor(0.35, 0.58, 0.72),
                new CharmColor(0.22, 0.36, 0.44),
                new CharmColor(0.11, 0.14, 0.22),
                new CharmColor(0.90, 0.90, 0.90)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "footballLegends",
            Region: "Argentina",
            Description: "Argentina's sky blue and white stripes with the ten on the back — the shirt a World Cup was finally won in.",
            Tags: ["Messi", "Argentina", "ten", "jersey"]),
        new(
            Id: "neymarJersey",
            DisplayName: "Neymar 10",
            FileName: "Football/Neymar 10.svg",
            Mass: 3.13,
            RadiusRatio: 0.1660,
            Palette: new CharmPalette(
                new CharmColor(0.87, 0.71, 0.02),
                new CharmColor(0.54, 0.44, 0.01),
                new CharmColor(0.14, 0.38, 0.15),
                new CharmColor(0.93, 0.83, 0.40)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "footballLegends",
            Region: "Brazil",
            Description: "Brazil's canarinho yellow, green at the collar and cuffs, ten on the back.",
            Tags: ["Neymar", "Brazil", "ten", "jersey"]),
        new(
            Id: "realMadridCrest",
            DisplayName: "Real Madrid",
            FileName: "Football/Real Madrid.svg",
            Mass: 3.18,
            RadiusRatio: 0.1664,
            Palette: new CharmPalette(
                new CharmColor(0.71, 0.53, 0.31),
                new CharmColor(0.44, 0.33, 0.19),
                new CharmColor(0.11, 0.09, 0.32),
                new CharmColor(0.92, 0.91, 0.89)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "footballLegends",
            Region: "Spain",
            Description: "The C, F and M interlocked under a royal crown — granted by Alfonso XIII in 1920, which is where the Real comes from.",
            Tags: ["Real Madrid", "crest", "crown", "Spain"]),
        new(
            Id: "fcBarcelonaCrest",
            DisplayName: "FC Barcelona",
            FileName: "Football/FC Barcelona.svg",
            Mass: 3.23,
            RadiusRatio: 0.1668,
            Palette: new CharmPalette(
                new CharmColor(0.46, 0.15, 0.29),
                new CharmColor(0.28, 0.09, 0.18),
                new CharmColor(0.30, 0.04, 0.19),
                new CharmColor(0.91, 0.86, 0.76)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "footballLegends",
            Region: "Spain",
            Description: "Blaugrana: the St George's cross and the Catalan bars above, the blue and claret halves below, a ball at the foot.",
            Tags: ["Barcelona", "crest", "blaugrana", "Catalonia"]),
        new(
            Id: "billieEilish",
            DisplayName: "Billie Eilish",
            FileName: "Music/Billie Eilish.svg",
            Mass: 2.62,
            RadiusRatio: 0.1672,
            Palette: new CharmPalette(
                new CharmColor(0.64, 0.62, 0.37),
                new CharmColor(0.40, 0.38, 0.23),
                new CharmColor(0.00, 0.00, 0.00),
                new CharmColor(0.73, 0.71, 0.49)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "musicLegends",
            Region: "United States",
            Description: "Green roots over black, sat down in oversized everything, looking like she would rather not be photographed.",
            Tags: ["Billie Eilish", "singer", "green", "music"]),
        new(
            Id: "xxxtentacion",
            DisplayName: "XXXTentacion",
            FileName: "Music/XXXTentacion.svg",
            Mass: 2.67,
            RadiusRatio: 0.1676,
            Palette: new CharmPalette(
                new CharmColor(0.66, 0.49, 0.34),
                new CharmColor(0.41, 0.30, 0.21),
                new CharmColor(0.00, 0.00, 0.00),
                new CharmColor(0.73, 0.57, 0.42)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "musicLegends",
            Region: "United States",
            Description: "Half-blond dreads and folded arms, sitting the way the album covers had him sit.",
            Tags: ["XXXTentacion", "rapper", "dreads", "music"]),
        new(
            Id: "michaelJackson",
            DisplayName: "Michael Jackson",
            FileName: "Music/Michael Jackson.svg",
            Mass: 2.72,
            RadiusRatio: 0.1680,
            Palette: new CharmPalette(
                new CharmColor(0.55, 0.30, 0.24),
                new CharmColor(0.34, 0.18, 0.15),
                new CharmColor(0.00, 0.00, 0.00),
                new CharmColor(0.76, 0.72, 0.68)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "musicLegends",
            Region: "United States",
            Description: "Caught mid-lean with the fedora down and one sequinned glove up — the pose that needs no caption anywhere on earth.",
            Tags: ["Michael Jackson", "pop", "fedora", "glove"]),
        new(
            Id: "taylorSwift",
            DisplayName: "Taylor Swift",
            FileName: "Music/Taylor Swift.svg",
            Mass: 2.78,
            RadiusRatio: 0.1684,
            Palette: new CharmPalette(
                new CharmColor(0.71, 0.52, 0.39),
                new CharmColor(0.44, 0.32, 0.24),
                new CharmColor(0.06, 0.04, 0.03),
                new CharmColor(0.82, 0.73, 0.67)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "musicLegends",
            Region: "United States",
            Description: "Sat on a flight case with an acoustic, which is where the songs start before a stadium gets involved.",
            Tags: ["Taylor Swift", "guitar", "songwriter", "music"]),
        new(
            Id: "juiceWrld",
            DisplayName: "Juice WRLD",
            FileName: "Music/Juice WRLD.svg",
            Mass: 2.84,
            RadiusRatio: 0.1688,
            Palette: new CharmPalette(
                new CharmColor(0.51, 0.34, 0.24),
                new CharmColor(0.32, 0.21, 0.15),
                new CharmColor(0.01, 0.00, 0.00),
                new CharmColor(0.68, 0.64, 0.60)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "musicLegends",
            Region: "United States",
            Description: "999 across the hoodie — his own number, six-six-six turned over, for taking a bad thing and making something of it.",
            Tags: ["Juice WRLD", "999", "rapper", "music"]),
        new(
            Id: "theWeeknd",
            DisplayName: "The Weeknd",
            FileName: "Music/The Weeknd.svg",
            Mass: 2.89,
            RadiusRatio: 0.1694,
            Palette: new CharmPalette(
                new CharmColor(0.61, 0.26, 0.24),
                new CharmColor(0.38, 0.16, 0.15),
                new CharmColor(0.00, 0.00, 0.00),
                new CharmColor(0.64, 0.40, 0.31)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "musicLegends",
            Region: "Canada",
            Description: "Sequined red jacket over black, arms out and eyes shut, halfway through the note that made the night famous.",
            Tags: ["The Weeknd", "singer", "red jacket", "music"]),
        new(
            Id: "rachelGreen",
            DisplayName: "Rachel Green",
            FileName: "Friends/Rachel Green.svg",
            Mass: 2.87,
            RadiusRatio: 0.1692,
            Palette: new CharmPalette(
                new CharmColor(0.64, 0.44, 0.32),
                new CharmColor(0.40, 0.28, 0.20),
                new CharmColor(0.06, 0.04, 0.03),
                new CharmColor(0.73, 0.60, 0.52)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "friends",
            Region: "United States",
            Description: "Coffee in hand, bag on the shoulder — which is how she spent a decent fraction of ten years.",
            Tags: ["Rachel", "Friends", "coffee", "New York"]),
        new(
            Id: "monicaGeller",
            DisplayName: "Monica Geller",
            FileName: "Friends/Monica Geller.svg",
            Mass: 2.92,
            RadiusRatio: 0.1696,
            Palette: new CharmPalette(
                new CharmColor(0.66, 0.47, 0.37),
                new CharmColor(0.41, 0.29, 0.23),
                new CharmColor(0.01, 0.01, 0.00),
                new CharmColor(0.69, 0.51, 0.41)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "friends",
            Region: "United States",
            Description: "Arms folded, all in black, and everything behind her exactly where it ought to be.",
            Tags: ["Monica", "Friends", "chef", "New York"]),
        new(
            Id: "rossGeller",
            DisplayName: "Ross Geller",
            FileName: "Friends/Ross Geller.svg",
            Mass: 2.98,
            RadiusRatio: 0.1702,
            Palette: new CharmPalette(
                new CharmColor(0.65, 0.46, 0.35),
                new CharmColor(0.41, 0.29, 0.21),
                new CharmColor(0.03, 0.02, 0.01),
                new CharmColor(0.71, 0.54, 0.43)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "friends",
            Region: "United States",
            Description: "Holding a dinosaur, because he is a palaeontologist and would like a moment of your time to explain it.",
            Tags: ["Ross", "Friends", "dinosaur", "New York"]),
        new(
            Id: "joeyTribbiani",
            DisplayName: "Joey Tribbiani",
            FileName: "Friends/Joey Tribbiani.svg",
            Mass: 3.03,
            RadiusRatio: 0.1706,
            Palette: new CharmPalette(
                new CharmColor(0.64, 0.44, 0.33),
                new CharmColor(0.40, 0.27, 0.20),
                new CharmColor(0.04, 0.03, 0.02),
                new CharmColor(0.74, 0.64, 0.58)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "friends",
            Region: "United States",
            Description: "Leather jacket, finger up, mouth open. You already know the line.",
            Tags: ["Joey", "Friends", "actor", "New York"]),
        new(
            Id: "chandlerBing",
            DisplayName: "Chandler Bing",
            FileName: "Friends/Chandler Bing.svg",
            Mass: 3.09,
            RadiusRatio: 0.1710,
            Palette: new CharmPalette(
                new CharmColor(0.61, 0.43, 0.34),
                new CharmColor(0.38, 0.27, 0.21),
                new CharmColor(0.04, 0.03, 0.02),
                new CharmColor(0.69, 0.54, 0.47)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "friends",
            Region: "United States",
            Description: "In the suit, hands in pockets, mid-sarcasm. Could his job BE any harder to describe?",
            Tags: ["Chandler", "Friends", "sarcasm", "New York"]),
        new(
            Id: "phoebeBuffay",
            DisplayName: "Phoebe Buffay",
            FileName: "Friends/Phoebe Buffay.svg",
            Mass: 3.14,
            RadiusRatio: 0.1714,
            Palette: new CharmPalette(
                new CharmColor(0.68, 0.45, 0.26),
                new CharmColor(0.42, 0.28, 0.16),
                new CharmColor(0.08, 0.04, 0.02),
                new CharmColor(0.77, 0.60, 0.48)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "friends",
            Region: "United States",
            Description: "Guitar in hand, which means a cat somewhere is about to be sung about at length.",
            Tags: ["Phoebe", "Friends", "guitar", "New York"]),
        new(
            Id: "walterWhite",
            DisplayName: "Walter White",
            FileName: "Breaking Bad/Walter White.svg",
            Mass: 3.28,
            RadiusRatio: 0.1718,
            Palette: new CharmPalette(
                new CharmColor(0.78, 0.56, 0.14),
                new CharmColor(0.48, 0.35, 0.09),
                new CharmColor(0.07, 0.05, 0.04),
                new CharmColor(0.89, 0.73, 0.47)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "breakingBad",
            Region: "United States",
            Description: "Yellow hazmat, a flask of blue in one hand and the gas mask in the other. Still telling himself it is about the family.",
            Tags: ["Walter White", "chemistry", "hazmat", "Breaking Bad"]),
        new(
            Id: "jessePinkman",
            DisplayName: "Jesse Pinkman",
            FileName: "Breaking Bad/Jesse Pinkman.svg",
            Mass: 3.33,
            RadiusRatio: 0.1722,
            Palette: new CharmPalette(
                new CharmColor(0.74, 0.51, 0.11),
                new CharmColor(0.46, 0.32, 0.07),
                new CharmColor(0.02, 0.02, 0.01),
                new CharmColor(0.80, 0.62, 0.35)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "breakingBad",
            Region: "United States",
            Description: "Beanie and a yellow jacket, standing like a man who has just been told off and is about to be told off again.",
            Tags: ["Jesse", "Breaking Bad", "beanie", "Albuquerque"]),
        new(
            Id: "saulGoodman",
            DisplayName: "Saul Goodman",
            FileName: "Breaking Bad/Saul Goodman.svg",
            Mass: 3.38,
            RadiusRatio: 0.1726,
            Palette: new CharmPalette(
                new CharmColor(0.76, 0.57, 0.34),
                new CharmColor(0.47, 0.35, 0.21),
                new CharmColor(0.03, 0.02, 0.02),
                new CharmColor(0.81, 0.62, 0.41)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "breakingBad",
            Region: "United States",
            Description: "Pinstripes, a loud tie and a sign carrying his own catchphrase, which is the most honest thing about him.",
            Tags: ["Saul", "lawyer", "Breaking Bad", "Albuquerque"]),
        new(
            Id: "gusFring",
            DisplayName: "Gus Fring",
            FileName: "Breaking Bad/Gus Fring.svg",
            Mass: 3.43,
            RadiusRatio: 0.1730,
            Palette: new CharmPalette(
                new CharmColor(0.54, 0.33, 0.21),
                new CharmColor(0.33, 0.21, 0.13),
                new CharmColor(0.01, 0.02, 0.02),
                new CharmColor(0.60, 0.47, 0.40)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "breakingBad",
            Region: "United States",
            Description: "The good suit, the glasses, and absolutely nothing showing on his face. That is the frightening part.",
            Tags: ["Gus Fring", "Los Pollos", "Breaking Bad", "suit"]),
        new(
            Id: "mikeEhrmantraut",
            DisplayName: "Mike Ehrmantraut",
            FileName: "Breaking Bad/Mike Ehrmantraut.svg",
            Mass: 3.48,
            RadiusRatio: 0.1734,
            Palette: new CharmPalette(
                new CharmColor(0.70, 0.47, 0.36),
                new CharmColor(0.43, 0.29, 0.22),
                new CharmColor(0.01, 0.01, 0.01),
                new CharmColor(0.76, 0.55, 0.44)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "breakingBad",
            Region: "United States",
            Description: "Leather jacket, hands where you can see them, and a patience you would be unwise to test.",
            Tags: ["Mike", "fixer", "Breaking Bad", "Albuquerque"]),
        new(
            Id: "heisenberg",
            DisplayName: "Heisenberg",
            FileName: "Breaking Bad/Heisenberg.svg",
            Mass: 3.53,
            RadiusRatio: 0.1738,
            Palette: new CharmPalette(
                new CharmColor(0.47, 0.39, 0.32),
                new CharmColor(0.29, 0.24, 0.20),
                new CharmColor(0.01, 0.01, 0.01),
                new CharmColor(0.55, 0.47, 0.41)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "breakingBad",
            Region: "United States",
            Description: "The porkpie hat, the glasses, a bag in one hand and the product in the other. The same man as the hazmat, further along.",
            Tags: ["Heisenberg", "hat", "Breaking Bad", "alias"]),
        new(
            Id: "rv",
            DisplayName: "RV",
            FileName: "Breaking Bad/RV.svg",
            Mass: 3.58,
            RadiusRatio: 0.1766,
            Palette: new CharmPalette(
                new CharmColor(0.81, 0.64, 0.40),
                new CharmColor(0.50, 0.40, 0.25),
                new CharmColor(0.03, 0.02, 0.01),
                new CharmColor(0.94, 0.82, 0.66)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "breakingBad",
            Region: "United States",
            Description: "The Fleetwood Bounder, sun-bleached and desert-dented, that did the cooking before anybody had a laboratory. The most recognisable vehicle on television.",
            Tags: ["RV", "Fleetwood", "desert", "lab", "Breaking Bad"]),
        new(
            Id: "eleven",
            DisplayName: "Eleven",
            FileName: "Stranger Things/Eleven.svg",
            Mass: 2.24,
            RadiusRatio: 0.1742,
            Palette: new CharmPalette(
                new CharmColor(0.69, 0.45, 0.34),
                new CharmColor(0.43, 0.28, 0.21),
                new CharmColor(0.07, 0.07, 0.08),
                new CharmColor(0.78, 0.65, 0.61)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "strangerThings",
            Region: "Hawkins, Indiana",
            Description: "Pink dress, buzzed hair, one hand out. The nosebleed comes after.",
            Tags: ["Eleven", "Hawkins", "powers", "Stranger Things"]),
        new(
            Id: "mikeWheeler",
            DisplayName: "Mike Wheeler",
            FileName: "Stranger Things/Mike Wheeler.svg",
            Mass: 2.28,
            RadiusRatio: 0.1746,
            Palette: new CharmPalette(
                new CharmColor(0.61, 0.42, 0.32),
                new CharmColor(0.38, 0.26, 0.20),
                new CharmColor(0.02, 0.02, 0.01),
                new CharmColor(0.71, 0.57, 0.49)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "strangerThings",
            Region: "Hawkins, Indiana",
            Description: "Walkie-talkie up, waiting on a reply from someone who may not be able to answer.",
            Tags: ["Mike", "Hawkins", "walkie-talkie", "Stranger Things"]),
        new(
            Id: "dustinHenderson",
            DisplayName: "Dustin Henderson",
            FileName: "Stranger Things/Dustin Henderson.svg",
            Mass: 2.33,
            RadiusRatio: 0.1750,
            Palette: new CharmPalette(
                new CharmColor(0.65, 0.43, 0.31),
                new CharmColor(0.40, 0.27, 0.19),
                new CharmColor(0.04, 0.02, 0.01),
                new CharmColor(0.80, 0.69, 0.64)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "strangerThings",
            Region: "Hawkins, Indiana",
            Description: "Cap on, headset on, halfway through a sentence and not slowing down for anybody.",
            Tags: ["Dustin", "Hawkins", "radio", "Stranger Things"]),
        new(
            Id: "lucasSinclair",
            DisplayName: "Lucas Sinclair",
            FileName: "Stranger Things/Lucas Sinclair.svg",
            Mass: 2.38,
            RadiusRatio: 0.1754,
            Palette: new CharmPalette(
                new CharmColor(0.48, 0.26, 0.15),
                new CharmColor(0.30, 0.16, 0.09),
                new CharmColor(0.04, 0.02, 0.01),
                new CharmColor(0.66, 0.54, 0.45)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "strangerThings",
            Region: "Hawkins, Indiana",
            Description: "Camo bandana and a wrist-rocket, drawn and aimed. The only one of them who came prepared.",
            Tags: ["Lucas", "Hawkins", "slingshot", "Stranger Things"]),
        new(
            Id: "willByers",
            DisplayName: "Will Byers",
            FileName: "Stranger Things/Will Byers.svg",
            Mass: 2.44,
            RadiusRatio: 0.1758,
            Palette: new CharmPalette(
                new CharmColor(0.65, 0.42, 0.23),
                new CharmColor(0.40, 0.26, 0.15),
                new CharmColor(0.06, 0.03, 0.01),
                new CharmColor(0.77, 0.61, 0.43)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "strangerThings",
            Region: "Hawkins, Indiana",
            Description: "Holding the string of Christmas lights his mother nailed to the wall to spell things out, letter by letter.",
            Tags: ["Will", "Hawkins", "lights", "Stranger Things"]),
        new(
            Id: "demogorgon",
            DisplayName: "Demogorgon",
            FileName: "Stranger Things/Demogorgon.svg",
            Mass: 2.48,
            RadiusRatio: 0.1762,
            Palette: new CharmPalette(
                new CharmColor(0.57, 0.24, 0.19),
                new CharmColor(0.36, 0.15, 0.12),
                new CharmColor(0.09, 0.02, 0.01),
                new CharmColor(0.67, 0.52, 0.47)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "strangerThings",
            Region: "Hawkins, Indiana",
            Description: "The face opens into five petals. That is the whole of what anybody needs to know about it.",
            Tags: ["Demogorgon", "Upside Down", "monster", "Stranger Things"]),
        new(
            Id: "circle",
            DisplayName: "Bead",
            FileName: "Bead.svg",
            Mass: 2.6,
            RadiusRatio: 0.140,
            Palette: new CharmPalette(
                new CharmColor(0.12, 0.20, 0.66),
                new CharmColor(0.07, 0.12, 0.44),
                new CharmColor(0.03, 0.06, 0.24),
                new CharmColor(0.46, 0.58, 0.95)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "classic",
            Region: "Universal",
            Description: "A plain glass bead, the charm Hangly ships with. Simple, weighty and never out of place.",
            Tags: ["bead", "simple", "default", "violet"]),
        new(
            Id: "camera",
            DisplayName: "Camera",
            FileName: "Camera.svg",
            Mass: 4.2,
            RadiusRatio: 0.170,
            Palette: new CharmPalette(
                new CharmColor(0.36, 0.38, 0.43),
                new CharmColor(0.20, 0.22, 0.26),
                new CharmColor(0.09, 0.10, 0.12),
                new CharmColor(0.74, 0.77, 0.82)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "classic",
            Region: "Universal",
            Description: "For photographers and the perpetually nostalgic. The heaviest charm in the box.",
            Tags: ["camera", "photo", "graphite", "heavy"]),
        new(
            Id: "star",
            DisplayName: "Star",
            FileName: "Star.svg",
            Mass: 2.2,
            RadiusRatio: 0.157,
            Palette: new CharmPalette(
                new CharmColor(1.00, 0.78, 0.25),
                new CharmColor(0.93, 0.58, 0.10),
                new CharmColor(0.62, 0.35, 0.03),
                new CharmColor(1.00, 0.93, 0.70)),
            BeadCount: 1,
            BodyRun: 1,
            CategoryId: "classic",
            Region: "Universal",
            Description: "Everyone's first lucky charm. The lightest in the set, so it swings the fastest.",
            Tags: ["star", "gold", "light", "wish"]),
        new(
            Id: "heart",
            DisplayName: "Heart",
            FileName: "Heart.svg",
            Mass: 2.9,
            RadiusRatio: 0.149,
            Palette: new CharmPalette(
                new CharmColor(0.93, 0.70, 0.74),
                new CharmColor(0.82, 0.51, 0.57),
                new CharmColor(0.54, 0.29, 0.34),
                new CharmColor(1.00, 0.90, 0.92)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "classic",
            Region: "Universal",
            Description: "Worn on the sleeve, or in this case at the top of the screen.",
            Tags: ["heart", "red", "love"]),
        new(
            Id: "diamond",
            DisplayName: "Diamond",
            FileName: "Diamond.svg",
            Mass: 3.4,
            RadiusRatio: 0.142,
            Palette: new CharmPalette(
                new CharmColor(0.62, 0.88, 0.97),
                new CharmColor(0.35, 0.68, 0.88),
                new CharmColor(0.18, 0.42, 0.62),
                new CharmColor(0.90, 0.98, 1.00)),
            BeadCount: 0,
            BodyRun: 0,
            CategoryId: "classic",
            Region: "Universal",
            Description: "Cut, faceted and indestructible. Heavy enough to hang the rope nearly straight.",
            Tags: ["gem", "ice", "faceted", "blue"]),
    ];
}
